2024-04-08 14:35:45,888 - KeyphraseVectorizer - INFO - It looks like you do not have downloaded a list of stopwords yet. It is attempted to download the stopwords now.
INFO:KeyphraseVectorizer:It looks like you do not have downloaded a list of stopwords yet. It is attempted to download the stopwords now.
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:997)>
Traceback (most recent call last):
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m

  Searched in:
    - '/home/petkovic/nltk_data'
    - '/opt/dev/Langs/Python/3.10.8/nltk_data'
    - '/opt/dev/Langs/Python/3.10.8/share/nltk_data'
    - '/opt/dev/Langs/Python/3.10.8/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratchbeta/petkovic/projet_charcot/./keyphrase-vectorizers.py", line 28, in <module>
    kp = kw_model.extract_keywords(data, vectorizer=vectorizer)
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/keybert/_model.py", line 158, in extract_keywords
    count = vectorizer.fit(docs)
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/keyphrase_vectorizers/keyphrase_count_vectorizer.py", line 163, in fit
    self.keyphrases = self._get_pos_keyphrases(document_list=raw_documents,
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/keyphrase_vectorizers/keyphrase_vectorizer_mixin.py", line 300, in _get_pos_keyphrases
    stop_words_list = set(nltk.corpus.stopwords.words(stop_words))
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/opt/dev/Langs/Python/3.10.8/lib/python3.10/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - '/home/petkovic/nltk_data'
    - '/opt/dev/Langs/Python/3.10.8/nltk_data'
    - '/opt/dev/Langs/Python/3.10.8/share/nltk_data'
    - '/opt/dev/Langs/Python/3.10.8/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

